version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:     
      POSTGRES_USER: eneko         # User for the database
      POSTGRES_PASSWORD: '${POSTGRE_PASS}'     # Password for the database user
      POSTGRES_DB: yourfirstdatajob   
    ports:
      - "5432:5432"                    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  